language: ruby
rvm:
  - 2.0.0
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
    - rvm: 1.9.3
      dist: trusty
script: bundle exec rake
before_install:
  - gem install bundler --version '< 2'
gemfile: .ci.gemfile
